name: Daily Headline Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python scraper.py
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add headlines.json
        git commit -m "Update headlines for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push || echo "Nothing to push"