name: Run Scraper and Update Data

on:
  schedule:
    # Run 4 times a day (every 6 hours: at 00:00, 06:00, 12:00, 18:00 UTC)
    # Note: GitHub Actions schedules can sometimes be delayed.
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  scrape_and_commit: # Job name
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    permissions:
      contents: write # Grant permission for the job to push commits

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Checks out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # Sets up the specified Python version
      with:
        # Ensure this Python version is compatible with your code and dependencies
        python-version: '3.12' # Or '3.9', '3.10', '3.11' etc. matching your needs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Installs packages listed in requirements.txt
        pip install -r requirements.txt

    - name: Run scraper script # Changed step name slightly for clarity
      env: # Pass secrets as environment variables to the Python script
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        MS_TRANSLATOR_KEY: ${{ secrets.MS_TRANSLATOR_KEY }}
        # Uncomment the next line if you have set MS_TRANSLATOR_REGION as a secret
        # and want to use it instead of the default 'global' in config.py
        MS_TRANSLATOR_REGION: ${{ secrets.MS_TRANSLATOR_REGION }}
      # Run the main entry point script now
      run: python main.py # <--- *** CHANGED SCRIPT NAME ***

    - name: Commit and push changes
      run: |
        # Print each command before executing it (debug)
        set -x

        # Configure Git user for commits made by this workflow
        echo "Configuring Git user..."
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        # Pull latest changes from the repository branch before committing
        echo "Pulling latest changes..."
        git pull

        # Check if the data file (headlines.json) has uncommitted changes
        echo "Checking for changes in headlines.json..."
        git diff --quiet --exit-code headlines.json
        EXIT_CODE=$? # Store exit code immediately
        echo "git diff exit code: $EXIT_CODE"

        if [ $EXIT_CODE -eq 0 ]; then
          echo "No changes detected in headlines.json. Nothing to commit."
          exit 0 # Exit this step successfully
        elif [ $EXIT_CODE -eq 1 ]; then
          # If exit code is 1, there are changes. Proceed.
          echo "Changes detected in headlines.json. Proceeding with commit..."
        else
          # Handle other potential git diff errors (exit code > 1)
          echo "git diff encountered an error (Exit Code: $EXIT_CODE)."
          exit $EXIT_CODE # Propagate the error
        fi

        # Stage the specific data file
        echo "Staging headlines.json..."
        git add headlines.json

        # Create commit message using the current date in Taipei Time (UTC+8)
        echo "Creating commit message..."
        COMMIT_DATE=$(TZ='Asia/Taipei' date +'%Y-%m-%d %H:%M CST')
        echo "Commit date string: $COMMIT_DATE"
        git commit -m "Update headlines for $COMMIT_DATE"

        # Push the commit to the repository's default branch (e.g., main)
        echo "Pushing changes..."
        git push

        # Turn off command printing (optional)
        set +x
        echo "Commit and push step completed successfully."
