name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or master, depending on your default branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Create site structure
        run: |
          # Remove docs directory if it exists and create fresh
          rm -rf docs
          mkdir -p docs
          
          # Create .nojekyll file
          touch docs/.nojekyll
          
          # Create a basic index.html
          cat > docs/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <title>China News Bot</title>
          </head>
          <body>
              <h1>China News Bot</h1>
              <p>Last updated: $(date)</p>
          </body>
          </html>
          EOL
          
          # List contents to verify
          ls -la docs/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate site content
        run: |
          python main.py
          # Verify docs directory content after generation
          echo "Contents of docs directory after generation:"
          ls -la docs/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true 