name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Create site content
        run: |
          # Create docs directory
          mkdir -p docs
          
          # Create .nojekyll file
          touch docs/.nojekyll
          
          # Create index.html
          cat > docs/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <title>China News Bot</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                  }
                  .header {
                      background-color: #f0f0f0;
                      padding: 20px;
                      border-radius: 8px;
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>China News Bot</h1>
                  <p>Last updated: $(date)</p>
              </div>
          </body>
          </html>
          EOL
          
          # List contents
          ls -la docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 