name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # IST to UTC conversion:
    # IST 00:00 (12 AM) = UTC 18:30 (previous day)
    # IST 06:00 (6 AM)  = UTC 00:30
    # IST 12:00 (12 PM) = UTC 06:30
    # IST 18:00 (6 PM)  = UTC 12:30
    - cron: '30 18,0,6,12 * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytz

      - name: Run scraper and generate site
        run: |
          # Run the scraper (which will use existing headlines.json)
          python main.py
          
          # Commit and push changes if any
          if git diff --quiet headlines.json; then
            echo "No changes to headlines.json"
          else
            git add headlines.json
            git commit -m "Update headlines.json [skip ci]"
            git push origin main
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 