name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Create site content
        run: |
          # Create docs directory
          mkdir -p docs
          
          # Create .nojekyll file
          touch docs/.nojekyll
          
          # Create index.html with some basic content
          cat > docs/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <title>China News Bot</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                  }
                  .header {
                      background-color: #f0f0f0;
                      padding: 20px;
                      border-radius: 8px;
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>China News Bot</h1>
                  <p>Last updated: $(date)</p>
              </div>
          </body>
          </html>
          EOL
          
          # Verify content was created
          ls -la docs/
          cat docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          enable_jekyll: false 