name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or 'master' if that's your default branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify exact version

      - name: Debug Python Environment
        run: |
          which python
          python --version
          pip --version
          echo "Python path:"
          python -c "import sys; print(sys.path)"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 --verbose
          pip freeze  # Show all installed packages
          pip install -r requirements.txt --verbose
          echo "After installing requirements:"
          pip freeze  # Show all installed packages again

      - name: Verify Jinja2 Installation
        run: |
          python -c "from jinja2 import Environment, FileSystemLoader; print('Jinja2 imported successfully')"

      - name: Generate site
        run: python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 